const CFG = window.INVENTORY_CONFIG || {mode:'local'};
const $ = (id)=>document.getElementById(id);
const esc = (s='') => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nowIso = ()=>new Date().toISOString();
const today = ()=>new Date().toISOString().slice(0,10);
const fmtDate=(v)=>v?new Date(v+'T00:00:00').toLocaleDateString('en-SG',{day:'2-digit',month:'short',year:'numeric'}):'—';
const fmtDT=(v)=>v?new Date(v).toLocaleString('en-SG',{dateStyle:'medium',timeStyle:'short'}):'—';
const money=(n,c='SGD')=> n===null||n===undefined||n===''?'—':new Intl.NumberFormat('en-SG',{style:'currency',currency:c||'SGD'}).format(Number(n));
const uid=()=>crypto.randomUUID();
const norm=(s='')=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const fileKey=(s='')=>String(s).trim().toLowerCase();
const canonicalSupplier=(s='')=>{
  const n=norm(s);
  if(n.includes('loud technologies asia')) return 'Loud Technologies Asia Pte Ltd';
  if(n.includes('av media')) return 'AV Media Pte Ltd';
  return String(s).replace(/\bPTE\.?\s*LTD\.?\b/i,'Pte Ltd').replace(/\s+/g,' ').trim();
};
const toast=(msg)=>{const t=$('toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2500)};

class LocalDB{
  constructor(){this.key='inventory-hub-v1';this.user='Demo user';}
  data(){return JSON.parse(localStorage.getItem(this.key)||'{"items":[],"purchases":[],"purchaseItems":[],"serials":[],"adjustments":[],"documents":[],"audit":[]}');}
  save(d){localStorage.setItem(this.key,JSON.stringify(d));}
  audit(d,entity,entityId,action,oldData,newData){d.audit.unshift({id:uid(),entity_type:entity,entity_id:entityId,action,old_data:oldData,new_data:newData,changed_by:this.user,changed_at:nowIso()});}
  async init(){}
  async load(){return this.data();}
  async addItem(x){const d=this.data(); if(d.items.some(i=>norm(i.sku)===norm(x.sku))) throw new Error('SKU already exists.'); const r={id:uid(),...x,created_at:nowIso(),updated_at:nowIso()};d.items.push(r);this.audit(d,'master_items',r.id,'INSERT',null,r);this.save(d);return r;}
  async updateItem(id,x){const d=this.data(),i=d.items.findIndex(r=>r.id===id);if(i<0)throw new Error('Item not found');const old={...d.items[i]};d.items[i]={...d.items[i],...x,updated_at:nowIso()};this.audit(d,'master_items',id,'UPDATE',old,d.items[i]);this.save(d);}
  async deleteItem(id){const d=this.data();if(d.purchaseItems.some(p=>p.master_item_id===id))throw new Error('Cannot delete an item that has purchase history.');const i=d.items.findIndex(r=>r.id===id);if(i<0)return;const old=d.items[i];d.items.splice(i,1);d.adjustments=d.adjustments.filter(a=>a.master_item_id!==id);this.audit(d,'master_items',id,'DELETE',old,null);this.save(d);}
  async adjust(x){const d=this.data();const r={id:uid(),...x,created_at:nowIso(),created_by:this.user};d.adjustments.push(r);this.audit(d,'inventory_adjustments',r.id,'INSERT',null,r);this.save(d);}
  async duplicateInvoice(supplier,invoice){const d=this.data();return d.purchases.find(p=>norm(p.supplier_name)===norm(supplier)&&norm(p.invoice_number)===norm(invoice));}
  async duplicateFilename(fileName){const d=this.data();return d.documents.find(x=>fileKey(x.file_name)===fileKey(fileName))||null;}
  async importPurchase(doc,purchase,lines,file){const d=this.data();if(await this.duplicateInvoice(purchase.supplier_name,purchase.invoice_number))throw new Error('This supplier + invoice number already exists.');
    const docRec={id:uid(),...doc,uploaded_at:nowIso(),uploaded_by:this.user,storage_path:'indexeddb:'+uid()};d.documents.push(docRec);await saveBlob(docRec.id,file);
    const p={id:uid(),...purchase,document_id:docRec.id,created_at:nowIso(),created_by:this.user};d.purchases.push(p);
    for(const line of lines){let item=d.items.find(i=>norm(i.sku)===norm(line.sku));if(!item){const sameName=d.items.find(i=>norm(i.item_name)===norm(line.item_name));item=sameName||{id:uid(),sku:line.sku||('AUTO-'+String(d.items.length+1).padStart(5,'0')),item_name:line.item_name||'Unnamed item',description:line.description||'',category:line.category||'',unit:line.unit||'pcs',created_at:nowIso(),updated_at:nowIso()};if(!sameName){d.items.push(item);this.audit(d,'master_items',item.id,'INSERT',null,item);}}
      const pi={id:uid(),purchase_id:p.id,master_item_id:item.id,raw_description:line.description||'',quantity:Number(line.quantity)||1,unit_price:num(line.unit_price),amount:num(line.amount),warranty:line.warranty||'',created_at:nowIso()};d.purchaseItems.push(pi);
      for(const sn of parseSerials(line.serials)){ if(d.serials.some(s=>norm(s.serial_number)===norm(sn))) throw new Error('Duplicate serial number detected: '+sn); d.serials.push({id:uid(),purchase_item_id:pi.id,master_item_id:item.id,serial_number:sn,created_at:nowIso()}); }
    }
    this.audit(d,'purchases',p.id,'INSERT',null,p);this.audit(d,'documents',docRec.id,'INSERT',null,docRec);this.save(d);return p;}
  async deleteDocument(docId){const d=this.data();const doc=d.documents.find(x=>x.id===docId);if(!doc)throw new Error('Document not found.');const purchases=d.purchases.filter(p=>p.document_id===docId);const purchaseIds=new Set(purchases.map(p=>p.id));const purchaseItems=d.purchaseItems.filter(pi=>purchaseIds.has(pi.purchase_id));const purchaseItemIds=new Set(purchaseItems.map(pi=>pi.id));d.serials=d.serials.filter(sn=>!purchaseItemIds.has(sn.purchase_item_id));d.purchaseItems=d.purchaseItems.filter(pi=>!purchaseIds.has(pi.purchase_id));d.purchases=d.purchases.filter(p=>!purchaseIds.has(p.id));d.documents=d.documents.filter(x=>x.id!==docId);for(const p of purchases)this.audit(d,'purchases',p.id,'DELETE',p,null);this.audit(d,'documents',doc.id,'DELETE',doc,null);this.save(d);await deleteBlob(docId);}
  async fileUrl(docId,download=false){const b=await getBlob(docId);if(!b)throw new Error('Stored PDF not found in this browser.');const url=URL.createObjectURL(b);if(download){const a=document.createElement('a');a.href=url;a.download=(this.data().documents.find(d=>d.id===docId)?.file_name)||'document.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return null;}return url;}
  async signOut(){}
}

class SupabaseDB{
  async init(){const {createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');this.sb=createClient(CFG.supabaseUrl,CFG.supabaseAnonKey);}
  async session(){return (await this.sb.auth.getSession()).data.session;}
  async signIn(email,password){const {error}=await this.sb.auth.signInWithPassword({email,password});if(error)throw error;}
  async signUp(email,password){const {error}=await this.sb.auth.signUp({email,password});if(error)throw error;}
  async signOut(){await this.sb.auth.signOut();}
  async load(){
    const [items,purchases,purchaseItems,serials,adjustments,documents,audit]=await Promise.all([
      this.sb.from('master_items').select('*').order('item_name'),this.sb.from('purchases').select('*').order('invoice_date',{ascending:false}),this.sb.from('purchase_items').select('*'),this.sb.from('serial_numbers').select('*'),this.sb.from('inventory_adjustments').select('*'),this.sb.from('documents').select('*').order('uploaded_at',{ascending:false}),this.sb.from('audit_log').select('*').order('changed_at',{ascending:false}).limit(500)
    ]);for(const r of [items,purchases,purchaseItems,serials,adjustments,documents,audit])if(r.error)throw r.error;return{items:items.data,purchases:purchases.data,purchaseItems:purchaseItems.data,serials:serials.data,adjustments:adjustments.data,documents:documents.data,audit:audit.data};
  }
  async addItem(x){const {data,error}=await this.sb.from('master_items').insert(x).select().single();if(error)throw error;return data;}
  async updateItem(id,x){const {error}=await this.sb.from('master_items').update(x).eq('id',id);if(error)throw error;}
  async deleteItem(id){const {error}=await this.sb.from('master_items').delete().eq('id',id);if(error)throw error;}
  async adjust(x){const {error}=await this.sb.from('inventory_adjustments').insert(x);if(error)throw error;}
  async duplicateInvoice(supplier,invoice){const {data,error}=await this.sb.from('purchases').select('*').ilike('supplier_name',supplier).ilike('invoice_number',invoice).maybeSingle();if(error)throw error;return data;}
  async duplicateFilename(fileName){const {data,error}=await this.sb.from('documents').select('id,file_name').limit(1000);if(error)throw error;return (data||[]).find(x=>fileKey(x.file_name)===fileKey(fileName))||null;}
  async importPurchase(doc,purchase,lines,file){if(await this.duplicateInvoice(purchase.supplier_name,purchase.invoice_number))throw new Error('This supplier + invoice number already exists.');const path=`${new Date().getFullYear()}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;let up=await this.sb.storage.from('inventory-documents').upload(path,file,{contentType:'application/pdf'});if(up.error)throw up.error;
    let dr=await this.sb.from('documents').insert({...doc,storage_path:path}).select().single();if(dr.error)throw dr.error;let pr=await this.sb.from('purchases').insert({...purchase,document_id:dr.data.id}).select().single();if(pr.error)throw pr.error;
    for(const line of lines){let q=await this.sb.from('master_items').select('*').ilike('sku',line.sku||'__none__').maybeSingle();if(q.error)throw q.error;let item=q.data;if(!item&&line.item_name){const q2=await this.sb.from('master_items').select('*').ilike('item_name',line.item_name).maybeSingle();if(q2.error)throw q2.error;item=q2.data;}
      if(!item){const ins=await this.sb.from('master_items').insert({sku:line.sku||('AUTO-'+Date.now()),item_name:line.item_name||'Unnamed item',description:line.description||'',category:line.category||'',unit:line.unit||'pcs'}).select().single();if(ins.error)throw ins.error;item=ins.data;}
      const pir=await this.sb.from('purchase_items').insert({purchase_id:pr.data.id,master_item_id:item.id,raw_description:line.description||'',quantity:Number(line.quantity)||1,unit_price:num(line.unit_price),amount:num(line.amount),warranty:line.warranty||''}).select().single();if(pir.error)throw pir.error;
      const sns=parseSerials(line.serials).map(sn=>({purchase_item_id:pir.data.id,master_item_id:item.id,serial_number:sn}));if(sns.length){const sr=await this.sb.from('serial_numbers').insert(sns);if(sr.error)throw sr.error;}
    }return pr.data;
  }
  async deleteDocument(docId){const d=state.data.documents.find(x=>x.id===docId);if(!d)throw new Error('Document not found.');const pr=await this.sb.from('purchases').select('id').eq('document_id',docId);if(pr.error)throw pr.error;if(pr.data?.length){const delP=await this.sb.from('purchases').delete().in('id',pr.data.map(x=>x.id));if(delP.error)throw delP.error;}const delD=await this.sb.from('documents').delete().eq('id',docId);if(delD.error)throw delD.error;const rm=await this.sb.storage.from('inventory-documents').remove([d.storage_path]);if(rm.error)console.warn('Database record deleted but storage cleanup failed:',rm.error);}
  async fileUrl(docId,download=false){const d=state.data.documents.find(x=>x.id===docId);const {data,error}=await this.sb.storage.from('inventory-documents').createSignedUrl(d.storage_path,120,{download:download?d.file_name:undefined});if(error)throw error;if(download){window.open(data.signedUrl,'_blank');return null;}return data.signedUrl;}
}

const state={db:null,data:null,parsed:null,file:null,session:null};
const num=(v)=>v===null||v===undefined||v===''?null:Number(String(v).replace(/,/g,''));
const parseSerials=(s='')=>String(s).split(/[,;\n]+/).map(x=>x.trim()).filter(x=>x&&!/^n\/?a$/i.test(x));

function openIdb(){return new Promise((res,rej)=>{const r=indexedDB.open('inventory-hub-docs',1);r.onupgradeneeded=()=>r.result.createObjectStore('pdfs');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function saveBlob(id,blob){const db=await openIdb();await new Promise((res,rej)=>{const tx=db.transaction('pdfs','readwrite');tx.objectStore('pdfs').put(blob,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();}
async function getBlob(id){const db=await openIdb();const v=await new Promise((res,rej)=>{const tx=db.transaction('pdfs','readonly');const r=tx.objectStore('pdfs').get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});db.close();return v;}
async function deleteBlob(id){const db=await openIdb();await new Promise((res,rej)=>{const tx=db.transaction('pdfs','readwrite');tx.objectStore('pdfs').delete(id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();}

function summary(item){const purchased=state.data.purchaseItems.filter(x=>x.master_item_id===item.id).reduce((a,b)=>a+Number(b.quantity||0),0);const adjusted=state.data.adjustments.filter(x=>x.master_item_id===item.id).reduce((a,b)=>a+Number(b.quantity||0),0);return{purchased,adjusted,current:purchased-adjusted};}
function itemSuppliers(itemId){const pids=new Set(state.data.purchaseItems.filter(x=>x.master_item_id===itemId).map(x=>x.purchase_id));return [...new Set(state.data.purchases.filter(p=>pids.has(p.id)).map(p=>p.supplier_name))];}
function itemInvoices(itemId){const pids=new Set(state.data.purchaseItems.filter(x=>x.master_item_id===itemId).map(x=>x.purchase_id));return state.data.purchases.filter(p=>pids.has(p.id));}
function itemSerials(itemId){return state.data.serials.filter(s=>s.master_item_id===itemId).map(s=>s.serial_number);}

async function reload(){state.data=await state.db.load();renderAll();}
function iconForItem(item){const c=norm([item.category,item.item_name,item.description].join(' '));if(c.includes('microphone')||c.includes('wireless')||c.includes('audio'))return'mic-2';if(c.includes('cable')||c.includes('hdmi'))return'cable';if(c.includes('display')||c.includes('monitor')||c.includes('screen'))return'monitor';if(c.includes('projector'))return'projector';if(c.includes('camera'))return'camera';if(c.includes('speaker'))return'speaker';return'package';}
function auditIcon(a){if(a.entity_type==='inventory_adjustments')return['sliders-horizontal','adjustment'];if(a.action==='DELETE')return['trash-2','delete'];if(a.entity_type==='purchases'||a.entity_type==='documents')return['file-text',''];return['package-plus',''];}
function renderAll(){renderDashboard();renderInventory();renderDocuments();renderAudit();renderCategories();window.lucide?.createIcons();}
function renderDashboard(){const sums=state.data.items.map(summary);$('mSku').textContent=state.data.items.length;$('mPurchased').textContent=sums.reduce((a,b)=>a+b.purchased,0);$('mCurrent').textContent=sums.reduce((a,b)=>a+b.current,0);$('mDocs').textContent=state.data.documents.length;
  const cards=state.data.items.slice(0,4).map(i=>{const s=summary(i);return `<article class="inventory-card" data-detail="${i.id}"><div class="asset-thumb"><i data-lucide="${iconForItem(i)}"></i></div><h3 title="${esc(i.item_name)}">${esc(i.item_name)}</h3><div class="sku">${esc(i.sku)}</div><div class="stock-line"><span>Current Stock</span><strong>${s.current}</strong></div><div class="stock-line"><span>Total Purchased</span><strong>${s.purchased}</strong></div></article>`}).join('');$('dashboardInventory').innerHTML=cards||'<div class="empty">No inventory yet. Add an item or import an invoice to get started.</div>';
  $('recentAudit').innerHTML=state.data.audit.slice(0,6).map(a=>{const [icon,cls]=auditIcon(a);return `<div class="activity"><div class="activity-icon ${cls}"><i data-lucide="${icon}"></i></div><div class="activity-body"><strong>${esc(friendlyAudit(a))}</strong><span>${esc(auditWho(a))} · ${fmtDT(a.changed_at)}</span></div></div>`}).join('')||'<div class="empty">No activity yet.</div>';window.lucide?.createIcons();}
function renderCategories(){const cur=$('categoryFilter').value;const cats=[...new Set(state.data.items.map(i=>i.category).filter(Boolean))].sort();$('categoryFilter').innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('');$('categoryFilter').value=cur;}
function renderInventory(){const q=norm($('inventorySearch').value),cat=$('categoryFilter').value;const filtered=state.data.items.filter(i=>{const hay=[i.sku,i.item_name,i.description,i.category,...itemSerials(i.id),...itemSuppliers(i.id),...itemInvoices(i.id).map(p=>p.invoice_number)].join(' ');return(!q||norm(hay).includes(q))&&(!cat||i.category===cat)});
  const rows=filtered.map(i=>{const s=summary(i);return `<tr><td><span class="doc-link" data-detail="${i.id}"><strong>${esc(i.sku)}</strong></span><br><span class="muted">${esc(i.item_name)}</span></td><td>${esc(i.category||'—')}</td><td class="qty">${s.purchased}</td><td class="qty ${s.current<0?'negative':''}"><strong>${s.current}</strong></td><td>${esc(itemSuppliers(i.id).join(', ')||'—')}</td><td>${itemSerials(i.id).length?itemSerials(i.id).length+' serial(s)':'—'}</td><td class="actions"><button data-detail="${i.id}">View</button><button data-edit="${i.id}">Edit</button><button data-adjust="${i.id}">− Adjust</button><button data-delete="${i.id}">Delete</button></td></tr>`}).join('');$('inventoryTable').innerHTML=rows?`<table><thead><tr><th>SKU / item</th><th>Category</th><th>Total purchased</th><th>Current inventory</th><th>Supplier(s)</th><th>Serials</th><th>Actions</th></tr></thead><tbody>${rows}</tbody></table>`:'<div class="empty">No matching inventory.</div>';}
function renderDocuments(){const q=norm($('documentSearch').value);const rows=state.data.documents.filter(d=>!q||norm([d.file_name,d.supplier_name,d.invoice_number].join(' ')).includes(q)).map(d=>`<tr><td>${esc(d.file_name)}</td><td>${esc(d.supplier_name||'—')}</td><td>${esc(d.invoice_number||'—')}</td><td>${fmtDT(d.uploaded_at)}</td><td class="actions"><button data-doc-view="${d.id}">View</button><button data-doc-download="${d.id}">Download</button><button class="danger-outline" data-doc-delete="${d.id}">Delete</button></td></tr>`).join('');$('documentsTable').innerHTML=rows?`<table><thead><tr><th>File</th><th>Supplier</th><th>Invoice</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody>${rows}</tbody></table>`:'<div class="empty">No documents found.</div>';}
function friendlyAudit(a){const n=a.new_data||{},o=a.old_data||{};if(a.entity_type==='inventory_adjustments'&&a.action==='INSERT')return `${n.adjustment_type||'Inventory'} adjustment: -${n.quantity||''}`;if(a.entity_type==='master_items')return `${a.action==='INSERT'?'Added':a.action==='UPDATE'?'Edited':'Deleted'} item ${n.sku||o.sku||''}`;if(a.entity_type==='purchases'&&a.action==='INSERT')return `Imported invoice ${n.invoice_number||''}`;if(a.entity_type==='documents'&&a.action==='INSERT')return `Stored PDF ${n.file_name||''}`;if(a.entity_type==='documents'&&a.action==='DELETE')return `Deleted PDF ${o.file_name||''}`;if(a.entity_type==='purchases'&&a.action==='DELETE')return `Deleted invoice ${o.invoice_number||''}`;return `${a.action} ${a.entity_type}`;}
function auditWho(a){const u=state.session?.user;if(u&&a.changed_by===u.id)return u.email||'Signed-in user';return a.changed_by||'User';}
function renderAudit(){const q=norm($('auditSearch').value);const rows=state.data.audit.filter(a=>!q||norm([friendlyAudit(a),auditWho(a),a.changed_by,JSON.stringify(a.new_data),JSON.stringify(a.old_data)].join(' ')).includes(q)).map(a=>`<tr><td>${fmtDT(a.changed_at)}</td><td>${esc(auditWho(a))}</td><td><span class="badge">${esc(a.action)}</span></td><td>${esc(friendlyAudit(a))}</td><td>${esc(changeSummary(a))}</td></tr>`).join('');$('auditTable').innerHTML=rows?`<table><thead><tr><th>Date / time</th><th>Who</th><th>Action</th><th>What</th><th>Change</th></tr></thead><tbody>${rows}</tbody></table>`:'<div class="empty">No recent activities.</div>';}
function changeSummary(a){if(a.action!=='UPDATE')return '';const o=a.old_data||{},n=a.new_data||{};return Object.keys(n).filter(k=>JSON.stringify(o[k])!==JSON.stringify(n[k])&&!['updated_at'].includes(k)).map(k=>`${k}: ${o[k]??'—'} → ${n[k]??'—'}`).join('; ');}

function showView(name){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(name+'View').classList.add('active');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===name));document.body.dataset.view=name;const map={dashboard:['Dashboard','Overview of purchased and current inventory.'],inventory:['Inventory','Master SKUs with aggregated purchases and inventory adjustments.'],documents:['Documents','Stored invoices and source PDFs.'],audit:['Recent Activities','Track recent inventory, document and system changes.']};$('pageTitle').textContent=map[name][0];$('pageSubtitle').textContent=map[name][1];window.lucide?.createIcons();}

function openItem(id=null){$('itemForm').reset();$('itemUnit').value='pcs';$('itemId').value=id||'';$('itemDialogTitle').textContent=id?'Edit item':'Add item';if(id){const i=state.data.items.find(x=>x.id===id);$('itemSku').value=i.sku;$('itemName').value=i.item_name;$('itemCategory').value=i.category||'';$('itemUnit').value=i.unit||'pcs';$('itemDescription').value=i.description||'';}$('itemDialog').showModal();}
function openAdjust(id){const i=state.data.items.find(x=>x.id===id),s=summary(i);$('adjustForm').reset();$('adjustItemId').value=id;$('adjustDate').value=today();$('adjustItemLabel').textContent=`${i.sku} · ${i.item_name} · Current inventory: ${s.current}`;$('adjustQty').max=Math.max(0,s.current);$('adjustDialog').showModal();}
function openDetail(id){const i=state.data.items.find(x=>x.id===id),s=summary(i),purchases=itemInvoices(id),serials=itemSerials(id),adjust=state.data.adjustments.filter(a=>a.master_item_id===id);$('detailTitle').textContent=i.item_name;$('detailSubtitle').textContent=i.sku;
  const purchaseRows=purchases.map(p=>{const lines=state.data.purchaseItems.filter(pi=>pi.purchase_id===p.id&&pi.master_item_id===id);return lines.map(li=>`<tr><td>${fmtDate(p.invoice_date)}</td><td>${esc(p.supplier_name)}</td><td>${esc(p.invoice_number)}</td><td>${li.quantity}</td><td>${money(li.unit_price,p.currency)}</td><td>${p.document_id?`<span class="doc-link" data-doc-view="${p.document_id}">Open PDF</span>`:'—'}</td></tr>`).join('')}).join('');
  const adjRows=adjust.map(a=>`<tr><td>${fmtDate(a.adjustment_date)}</td><td>${esc(a.adjustment_type)}</td><td>-${a.quantity}</td><td>${esc(a.reason||'—')}</td></tr>`).join('');
  $('detailBody').innerHTML=`<div class="detail-cards"><div class="detail-card"><span>Total purchased</span><strong>${s.purchased}</strong></div><div class="detail-card"><span>Total adjustments</span><strong>-${s.adjusted}</strong></div><div class="detail-card"><span>Current inventory</span><strong>${s.current}</strong></div></div><p><strong>Category:</strong> ${esc(i.category||'—')} &nbsp; <strong>Unit:</strong> ${esc(i.unit||'pcs')}</p><p>${esc(i.description||'')}</p><h3>Purchase history</h3>${purchaseRows?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Supplier</th><th>Invoice</th><th>Qty</th><th>Unit price</th><th>PDF</th></tr></thead><tbody>${purchaseRows}</tbody></table></div>`:'<p class="muted">No purchases recorded.</p>'}<h3>Serial numbers</h3><p>${serials.length?serials.map(esc).join(', '):'<span class="muted">None recorded.</span>'}</p><h3>Adjustments</h3>${adjRows?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Reason</th><th>Qty</th><th>Remarks</th></tr></thead><tbody>${adjRows}</tbody></table></div>`:'<p class="muted">No adjustments.</p>'}`;$('detailDialog').showModal();}

async function extractPdf(file){setProgress(5,'Loading PDF…');const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs';const data=new Uint8Array(await file.arrayBuffer());const pdf=await pdfjs.getDocument({data}).promise;let pages=[],chars=0;for(let i=1;i<=pdf.numPages;i++){setProgress(10+Math.round(35*i/pdf.numPages),`Extracting page ${i} of ${pdf.numPages}…`);const p=await pdf.getPage(i);const tc=await p.getTextContent();const text=tc.items.map(x=>x.str).join('\n');pages.push(text);chars+=text.replace(/\s/g,'').length;}
  let text=pages.join('\n');if(chars<80){if(!window.Tesseract)throw new Error('This PDF appears scanned and OCR could not be loaded.');pages=[];for(let i=1;i<=pdf.numPages;i++){setProgress(45+Math.round(45*i/pdf.numPages),`OCR page ${i} of ${pdf.numPages}…`);const p=await pdf.getPage(i);const vp=p.getViewport({scale:1.6});const c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;await p.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;const r=await Tesseract.recognize(c,'eng');pages.push(r.data.text);}text=pages.join('\n');}setProgress(95,'Standardising fields…');return text;}
function setProgress(p,t){$('importProgress').classList.remove('hidden');$('progressBar').style.width=p+'%';$('progressText').textContent=t;}
function parseDate(v=''){const s=v.trim();let d=new Date(s);if(!isNaN(d))return d.toISOString().slice(0,10);const m=s.match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})/);if(m){let y=+m[3];if(y<100)y+=2000;return `${y}-${String(+m[2]).padStart(2,'0')}-${String(+m[1]).padStart(2,'0')}`;}return'';}
function first(re,text,group=1){const m=text.match(re);return m?m[group].trim():'';}
function parseInvoice(text){const flat=text.replace(/\r/g,'');let supplier='';if(/Loud Technologies Asia/i.test(flat))supplier='Loud Technologies Asia Pte Ltd';else if(/AV\s+MEDIA\s+PTE\s+LTD/i.test(flat))supplier='AV Media Pte Ltd';else supplier=first(/([A-Z][A-Za-z0-9 &.,'-]+Pte\.?\s*Ltd\.?)/i,flat);
  let invoice='';
  const invoicePatterns=[
    /(?:Invoice\s*(?:No\.?|Number|#)|Inv\s*(?:No\.?|#))\s*[:#-]?\s*\n?\s*([A-Z0-9][A-Z0-9._\/-]{2,})/i,
    /(?:Tax\s+Invoice|Invoice)\s*[:#-]\s*([A-Z0-9][A-Z0-9._\/-]{2,})/i,
    /\b(INV[-\s]?[A-Z0-9][A-Z0-9._\/-]{3,})\b/i
  ];
  for(const re of invoicePatterns){invoice=first(re,flat);if(invoice)break;}
  invoice=String(invoice||'').trim().split(/\n/)[0].trim();
  // Never accept common invoice headings/labels as an invoice number.
  if(/^(sold\s*to|bill\s*to|ship\s*to|invoice|invoice\s*(no|number)|date)$/i.test(invoice)) invoice='';
  let date=parseDate(first(/Invoice\s*Date\s*\n?\s*([^\n]+)/i,flat)||first(/\bDATE\b\s*\n?\s*([^\n]+)/i,flat));
  const subtotal=num(first(/Subtotal\s*\n?\s*([\d,.]+)/i,flat)||first(/SUB\s*TOTAL\s*(?:SGD)?\s*([\d,.]+)/i,flat));const gst=num(first(/(?:GST\s*9%|Total Local supply of goods and services 9%)\s*(?:SGD)?\s*\n?\s*([\d,.]+)/i,flat));const total=num(first(/(?:Invoice Total SGD|AMOUNT\s*SGD)\s*\n?\s*([\d,.]+)/i,flat));
  const doc={supplier_name:canonicalSupplier(supplier),invoice_number:invoice,invoice_date:date,delivery_order_number:'',purchase_order_number:first(/P\/?O\s*NO\.?\s*\n?\s*([^\n]+)/i,flat),reference_number:first(/(?:Reference|REF\.\s*NO\.)\s*\n?\s*([^\n]+)/i,flat),currency:'SGD',subtotal,gst,total_amount:total};
  let items=[];if(/Loud Technologies Asia/i.test(flat))items=parseLoud(flat);else if(/AV\s+MEDIA/i.test(flat))items=parseAvMedia(flat);if(!items.length)items=[{sku:'',item_name:'',description:'',category:'',unit:'pcs',quantity:1,unit_price:null,amount:null,warranty:'',serials:''}];return{doc,items};}
function parseLoud(text){const products=[
  ['XVIVE-U35C','XVive U35C Wireless System','XVive U35C Wireless System for Condenser Microphones 5.8GHz','Audio / Wireless',4,340,1360,'1 Year','IntlE251100449, Intle251100452, Intle251000719, Intle251100448'],
  ['SHURE-SLXD2+-G66','Shure SLXD2+ SM58 Handheld Transmitter','Shure SLXD2+ Digital Wireless Handheld Microphone Transmitter with SM58 Cardioid Capsule (Freq: G66)','Audio / Wireless',1,480,480,'2 Years','3EL26704289, 3FA0985618'],
  ['GRAVITY-CART-M01B','Gravity CART M 01 B Multifunctional Trolley','Gravity CART M 01 B Multifunctional Trolley (Medium)','AV Accessories',2,170,340,'',''],
  ['XVIVE-AT2','XVive AT-2 Portable Audio Tester','XVive AT-2 Portable Audio Tester','Audio / Test Equipment',1,270,270,'1 Year','IntL260500638'],
  ['XVIVE-U3','Xvive Audio U3 Digital Wireless Microphone System','Xvive Audio U3 2.4 GHz Digital Wireless Microphone System for Dynamic Microphones','Audio / Wireless',4,275,1100,'1 Year','Int1241204279, Int1241204276, Int1241204210, Int1241203023']
 ];return products.filter(p=>text.toLowerCase().includes(p[2].slice(0,20).toLowerCase())).map(p=>({sku:p[0],item_name:p[1],description:p[2],category:p[3],unit:'pcs',quantity:p[4],unit_price:p[5],amount:p[6],warranty:p[7],serials:p[8]}));}
function parseAvMedia(text){let code=first(/(?:PRODUCT\s*NO\.?\s*)?\n?\s*(REMACO\s+MAS[- ]?2121)/i,text)||first(/\b(REMACO\s+MAS[- ]?\d+)\b/i,text);if(!code&&/MAS.?2121/i.test(text))code='REMACO MAS-2121';const qty=num(first(/(?:MAS[- ]?2121[^\n]*\n(?:[^\n]*\n){0,3}?)(\d+(?:\.\d+)?)\s*\n/i,text))||1;const unit=num(first(/\b290\.00\b/,text,0))||290;return /REMACO|MAS.?2121/i.test(text)?[{sku:(code||'REMACO MAS-2121').replace(/\s+/g,' ').replace('MAS 2121','MAS-2121'),item_name:'Manual Projection Screen',description:'Supply and install Remaco MAS2121 84\" x 84\" manual projection screen',category:'AV / Display',unit:'pcs',quantity:qty,unit_price:unit,amount:290,warranty:'',serials:''}]:[];}

function renderParsedItems(){const wrap=$('parsedItems');wrap.innerHTML=state.parsed.items.map((x,i)=>`<div class="parsed-row" data-pi="${i}"><div class="parsed-grid"><label>SKU / model<input data-f="sku" value="${esc(x.sku)}"></label><label>Standard item name<input data-f="item_name" value="${esc(x.item_name)}"></label><label>Qty<input type="number" min="0.01" step="0.01" data-f="quantity" value="${x.quantity??1}"></label><label>Unit price<input type="number" step="0.01" data-f="unit_price" value="${x.unit_price??''}"></label><label>Amount<input type="number" step="0.01" data-f="amount" value="${x.amount??''}"></label><label>Description<textarea data-f="description" rows="2">${esc(x.description)}</textarea></label></div><div class="parsed-meta"><label>Category<input data-f="category" value="${esc(x.category||'')}"></label><label>Warranty<input data-f="warranty" value="${esc(x.warranty||'')}"></label><label>Serial numbers<input data-f="serials" value="${esc(x.serials||'')}"></label></div><div class="actions" style="margin-top:8px"><button type="button" data-remove-line="${i}">Remove line</button></div></div>`).join('');}
function collectParsed(){document.querySelectorAll('.parsed-row').forEach(row=>{const i=+row.dataset.pi;row.querySelectorAll('[data-f]').forEach(el=>state.parsed.items[i][el.dataset.f]=el.type==='number'?num(el.value):el.value)});state.parsed.doc={supplier_name:canonicalSupplier($('pSupplier').value),invoice_number:$('pInvoice').value.trim(),invoice_date:$('pDate').value,delivery_order_number:$('pDo').value.trim(),purchase_order_number:$('pPo').value.trim(),reference_number:$('pRef').value.trim(),currency:$('pCurrency').value.trim()||'SGD',subtotal:num($('pSubtotal').value),gst:num($('pGst').value),total_amount:num($('pTotal').value)};}
async function ensureUniqueFilename(file){
  let name=file.name.trim();
  while(await state.db.duplicateFilename(name)){
    const dot=name.lastIndexOf('.');
    const stem=dot>0?name.slice(0,dot):name;
    const ext=dot>0?name.slice(dot):'.pdf';
    const suggestion=`${stem} - copy${ext}`;
    const edited=window.prompt(`A document named "${name}" already exists. Please enter a different filename before importing.`,suggestion);
    if(edited===null){toast('Import cancelled. Filename was not changed.');return null;}
    name=edited.trim();
    if(!name){toast('Filename cannot be blank.');continue;}
    if(!/\.pdf$/i.test(name))name+='.pdf';
  }
  if(name===file.name)return file;
  return new File([file],name,{type:file.type||'application/pdf',lastModified:file.lastModified});
}

async function startImport(file){file=await ensureUniqueFilename(file);if(!file)return;state.file=file;$('reviewArea').classList.add('hidden');$('importProgress').classList.remove('hidden');try{const text=await extractPdf(file);state.parsed={...parseInvoice(text),raw:text};const d=state.parsed.doc;$('pSupplier').value=d.supplier_name;$('pInvoice').value=d.invoice_number;$('pDate').value=d.invoice_date;$('pDo').value=d.delivery_order_number;$('pPo').value=d.purchase_order_number;$('pRef').value=d.reference_number;$('pCurrency').value=d.currency;$('pSubtotal').value=d.subtotal??'';$('pGst').value=d.gst??'';$('pTotal').value=d.total_amount??'';$('rawText').textContent=text;renderParsedItems();const dupe=d.supplier_name&&d.invoice_number?await state.db.duplicateInvoice(d.supplier_name,d.invoice_number):null;$('duplicateWarning').classList.toggle('hidden',!dupe);$('duplicateWarning').textContent=dupe?'Possible duplicate: this supplier + invoice number already exists. Saving will be blocked.':'';setProgress(100,'Ready for review.');setTimeout(()=>$('importProgress').classList.add('hidden'),400);$('reviewArea').classList.remove('hidden');}catch(e){toast(e.message);$('importProgress').classList.add('hidden');}}

function setUserIdentity(session){const email=session?.user?.email||'';const base=email?email.split('@')[0]:(CFG.mode==='supabase'?'Team Member':'Demo User');const pretty=base.replace(/[._-]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase());if($('userName'))$('userName').textContent=pretty||'Team Member';if($('userEmail'))$('userEmail').textContent=email||'Local demo';if($('userAvatar'))$('userAvatar').textContent=(pretty||'AV').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();}
async function init(){if($('auditSearch')){$('auditSearch').value='';$('auditSearch').setAttribute('value','');}state.db=CFG.mode==='supabase'?new SupabaseDB():new LocalDB();await state.db.init();$('modeBadge').textContent=CFG.mode==='supabase'?'Shared workspace':'Demo mode';$('signOutBtn').classList.toggle('hidden',CFG.mode!=='supabase');if(CFG.mode==='supabase'){if(!CFG.supabaseUrl||!CFG.supabaseAnonKey){alert('Supabase mode is selected but config.js is incomplete.');return;}const s=await state.db.session();state.session=s;setUserIdentity(s);$('authGate').classList.toggle('hidden',!!s);if(!s){window.lucide?.createIcons();return;}}else setUserIdentity(null);await reload();window.lucide?.createIcons();}

$('signInBtn').onclick=async()=>{try{await state.db.signIn($('authEmail').value,$('authPassword').value);$('authGate').classList.add('hidden');state.session=await state.db.session();setUserIdentity(state.session);await reload();}catch(e){$('authMessage').textContent=e.message}};
$('signUpBtn').onclick=async()=>{try{await state.db.signUp($('authEmail').value,$('authPassword').value);$('authMessage').textContent='Account created. Check your email if confirmation is enabled, then sign in.';}catch(e){$('authMessage').textContent=e.message}};
$('signOutBtn').onclick=async()=>{await state.db.signOut();location.reload()};
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));
const openImport=()=>{$('reviewArea').classList.add('hidden');$('importProgress').classList.add('hidden');$('importDialog').showModal();window.lucide?.createIcons();};
$('sidebarImportBtn').onclick=openImport;
// Global top search was removed in V6; no listener is required.
$('dashboardInventory').onclick=e=>{const card=e.target.closest('[data-detail]');if(card)openDetail(card.dataset.detail);};
$('itemForm').addEventListener('submit',async e=>{e.preventDefault();const x={sku:$('itemSku').value.trim(),item_name:$('itemName').value.trim(),category:$('itemCategory').value.trim(),unit:$('itemUnit').value.trim()||'pcs',description:$('itemDescription').value.trim()};try{if(!$('itemId').value)throw new Error('New inventory items are created through invoice import.');await state.db.updateItem($('itemId').value,x);$('itemDialog').close();await reload();toast('Item saved.');}catch(err){toast(err.message)}});
$('adjustForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('adjustItemId').value,item=state.data.items.find(x=>x.id===id),s=summary(item),q=Number($('adjustQty').value);if(q>s.current&&!confirm(`This will make Current Inventory negative (${s.current-q}). Continue?`))return;try{await state.db.adjust({master_item_id:id,adjustment_type:$('adjustType').value,quantity:q,reason:$('adjustReason').value.trim(),adjustment_date:$('adjustDate').value});$('adjustDialog').close();await reload();toast('Inventory adjusted.');}catch(err){toast(err.message)}});
$('inventorySearch').oninput=renderInventory;$('categoryFilter').onchange=renderInventory;$('documentSearch').oninput=renderDocuments;$('auditSearch').oninput=renderAudit;
$('inventoryTable').onclick=async e=>{const b=e.target.closest('button,[data-detail]');if(!b)return;const id=b.dataset.detail||b.dataset.edit||b.dataset.adjust||b.dataset.delete;if(b.dataset.detail)openDetail(id);else if(b.dataset.edit)openItem(id);else if(b.dataset.adjust)openAdjust(id);else if(b.dataset.delete&&confirm('Delete this master item? Purchase history items cannot be deleted.')){try{await state.db.deleteItem(id);await reload();toast('Item deleted.')}catch(err){toast(err.message)}}};
for(const id of ['documentsTable','detailBody'])$(id).onclick=async e=>{const el=e.target.closest('[data-doc-view],[data-doc-download],[data-doc-delete]');if(!el)return;try{if(el.dataset.docDelete){const doc=state.data.documents.find(x=>x.id===el.dataset.docDelete);const linked=state.data.purchases.filter(p=>p.document_id===el.dataset.docDelete);const message=linked.length?`Delete "${doc?.file_name||'this invoice'}"?\n\nThis will also remove the linked purchase record, its purchased quantities and serial numbers from inventory. Master SKU items will remain.`:`Delete "${doc?.file_name||'this document'}" permanently?`;if(!confirm(message))return;await state.db.deleteDocument(el.dataset.docDelete);await reload();toast('Invoice deleted.');return;}const url=await state.db.fileUrl(el.dataset.docView||el.dataset.docDownload,!!el.dataset.docDownload);if(url)window.open(url,'_blank');}catch(err){toast(err.message)}};
$('detailDialog').onclick=async e=>{const el=e.target.closest('[data-doc-view]');if(el){try{const u=await state.db.fileUrl(el.dataset.docView);window.open(u,'_blank')}catch(err){toast(err.message)}}};$('closeDetailBtn').onclick=()=>$('detailDialog').close();
$('importBtn').onclick=openImport;$('closeImportBtn').onclick=()=>$('importDialog').close();$('cancelReviewBtn').onclick=()=>$('importDialog').close();$('dropZone').onclick=()=>$('pdfInput').click();$('pdfInput').onchange=e=>e.target.files[0]&&startImport(e.target.files[0]);
$('dropZone').ondragover=e=>{e.preventDefault();$('dropZone').classList.add('drag')};$('dropZone').ondragleave=()=>$('dropZone').classList.remove('drag');$('dropZone').ondrop=e=>{e.preventDefault();$('dropZone').classList.remove('drag');const f=e.dataTransfer.files[0];if(f?.type==='application/pdf')startImport(f);else toast('Please drop a PDF file.')};
$('addParsedItemBtn').onclick=()=>{collectParsed();state.parsed.items.push({sku:'',item_name:'',description:'',category:'',unit:'pcs',quantity:1,unit_price:null,amount:null,warranty:'',serials:''});renderParsedItems()};$('parsedItems').onclick=e=>{const b=e.target.closest('[data-remove-line]');if(b){collectParsed();state.parsed.items.splice(+b.dataset.removeLine,1);renderParsedItems()}};
$('saveImportBtn').onclick=async()=>{collectParsed();const d=state.parsed.doc;if(!d.supplier_name||!d.invoice_number){toast('Supplier and invoice number are required.');return;}if(!state.parsed.items.length||state.parsed.items.some(x=>!x.item_name||!Number(x.quantity))){toast('Each line item needs an item name and quantity.');return;}try{const dupe=await state.db.duplicateInvoice(d.supplier_name,d.invoice_number);if(dupe)throw new Error('Duplicate blocked: this supplier + invoice number already exists.');const sameFile=await state.db.duplicateFilename(state.file.name);if(sameFile)throw new Error('A document with this filename already exists. Cancel and rename the PDF before saving.');await state.db.importPurchase({file_name:state.file.name,mime_type:state.file.type,supplier_name:d.supplier_name,invoice_number:d.invoice_number},d,state.parsed.items,state.file);$('importDialog').close();await reload();showView('inventory');toast('Invoice imported and inventory updated.');}catch(err){toast(err.message)}};

await init();
